name: generate-ascii-artwork
on:
  -  push 
jobs:
  ascii-job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v6
        - name: list repo files
          run: ls -ltra  
        - name: executing shell script
          run: ./ascii-script.sh
          
        
                           